spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/solid-bank
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

solid:
  bank:
    api-key: '1234567891011121'