server.port: 9292

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5431/solid-bank
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog/master.xml
    contexts: ${spring.profiles.active}
  profiles:
    active: dev

logging:
  level:
    com.solid.soft.solid_soft_bank: debug

application:
  sample:
    card:

  temporary:
    otp: 12345
    threshold: 100.0
  payment:
    url: http://localhost:${server.port}/payment/ui/checkout
    otp-url: http://localhost:${server.port}/payment/ui/pay

#  http://localhost:9292/payment/ui/pay?
#  bankTransactionCode=2fe77e84-5cdc-1576-1rgytyuuw1805ae6a92be-136f-4ccf-9a75-aff0b58c2e3d1738591686918&
#  name=Donald&
#  surname=Trump&
#  cardNo=5105105105105100&
#  expiredDate=01%2F26&
#  cvc=123&amount=150.0&
#  currency=USD
