server.port: 9292

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5431/solid-bank
    username: postgres
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog/master.xml
    contexts: ${spring.profiles.active}
  profiles:
    active: dev

logging:
  level:
    com.solid.soft.solid_soft_bank: debug

application:
  sample:
    card:
      sample-card-no: '5105105105105100'
  temporary:
    otp: 12345
  payment:
    url: http://localhost:${server.port}/bank/checkout
    otp-url: http://localhost:${server.port}/bank/ui/pay?bankTransactionCode=